ci:
  autofix_prs: false
repos:
  - repo: 'https://github.com/pre-commit/pre-commit-hooks'
    rev: v4.5.0
    hooks:
      - id: mixed-line-ending
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-added-large-files
      - id: check-docstring-first
      - id: check-json
      - id: check-yaml
      - id: check-merge-conflict
      - id: name-tests-test
      - id: double-quote-string-fixer
  - repo: 'https://github.com/psf/black'
    rev: 23.9.1
    hooks:
      - id: black
  - repo: 'https://github.com/codespell-project/codespell'
    rev: v2.2.6
    hooks:
      - id: codespell
  - repo: 'https://github.com/charliermarsh/ruff-pre-commit'
    rev: v0.0.292
    hooks:
      - id: ruff
        args:
          - '--fix'
  - repo: 'https://github.com/pre-commit/mirrors-mypy'
    rev: v1.6.0
    hooks:
      - id: mypy
        additional_dependencies: [
            'discord-py>=2.0.0',
            'quart>=0.19.2',
            'types-emoji',
            'types-requests',
        ]
